server:
  port: 9081

spring:
  datasource:
    url: jdbc:h2:mem:mydb
#    ;database_to_upper=false;database_to_lower=false;case_insensitive_identifiers=true;
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

logging:
  pattern:
    console: '%d{HH:mm:ss} - %msg%n'
  level:
    org: WARN
    com: WARN
    ru.vk.competition.minbenchmark.MinbenchmarkApplication: WARN
    ru.vk.competition.minbenchmark.controller.TablesController: INFO
    ru.vk.competition.minbenchmark.controller.TableQueriesController: INFO
    ru.vk.competition.minbenchmark.controller.SingleQueriesController: INFO
    ru.vk.competition.minbenchmark.controller.ReportController: INFO
